export interface ExerciseLibraryItem {
  name: string
  type: string[]
  target: string[]
  synergist: string[]
}

export const EXERCISE_LIBRARY: ExerciseLibraryItem[] = [
  { name: 'Ab Wheel, Bodyweight', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'shoulders', 'back', 'chest', 'glutes'] },
  { name: 'Arnold Press, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Arnold Press, Kettlebell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Around The World, Dumbbell', type: ['core'], target: ['shoulders', 'chest'], synergist: ['back'] },
  { name: 'Back Extension, Bodyweight', type: ['lower', 'core'], target: ['back'], synergist: ['hamstrings', 'glutes'] },
  { name: 'Back Extension, Leverage Machine', type: ['lower', 'core'], target: ['back'], synergist: ['hamstrings', 'glutes'] },
  { name: 'Ball Slams, Medicine Ball', type: ['core', 'upper'], target: ['shoulders', 'back'], synergist: ['chest', 'abs'] },
  { name: 'Battle Ropes, Bodyweight', type: ['upper', 'core'], target: ['shoulders'], synergist: ['biceps', 'forearms', 'back'] },
  { name: 'Behind The Neck Press, Barbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Behind The Neck Press, Smith Machine', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Behind The Neck Press, Band', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Bench Dip, Bodyweight', type: ['upper', 'push'], target: ['triceps'], synergist: ['shoulders', 'back', 'chest'] },
  { name: 'Bench Press, Barbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bench Press, Cable', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bench Press, Dumbbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bench Press, Smith Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bench Press, Band', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bench Press, Kettlebell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bench Press Close Grip, Barbell', type: ['upper', 'push'], target: ['triceps'], synergist: ['shoulders', 'chest'] },
  { name: 'Bench Press Close Grip, Smith Machine', type: ['upper', 'push'], target: ['triceps'], synergist: ['shoulders', 'chest'] },
  { name: 'Bench Press Close Grip, EZ Bar', type: ['upper', 'push'], target: ['triceps'], synergist: ['shoulders', 'chest'] },
  { name: 'Bench Press Wide Grip, Barbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bench Press Wide Grip, Smith Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Bent Over One Arm Row, Dumbbell', type: ['upper', 'pull'], target: ['back'], synergist: ['shoulders', 'biceps', 'forearms', 'chest'] },
  { name: 'Bent Over Row, Barbell', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Bent Over Row, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Bent Over Row, Dumbbell', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Bent Over Row, Smith Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Bent Over Row, Band', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Bent Over Row, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Bicep Curl, Barbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Bicep Curl, Cable', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Bicep Curl, Dumbbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Bicep Curl, Band', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Bicep Curl, Leverage Machine', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Bicep Curl, EZ Bar', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Bicycle Crunch, Bodyweight', type: ['core'], target: ['abs'], synergist: ['glutes', 'quadriceps'] },
  { name: 'Box Squat, Barbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Box Squat, Dumbbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Bulgarian Split Squat, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Cable Crossover, Cable', type: ['upper', 'pull'], target: ['chest'], synergist: ['shoulders', 'back'] },
  { name: 'Cable Crunch, Cable', type: ['core'], target: ['abs'], synergist: ['cable kickback', 'cable'] },
  { name: 'Cable Kickback, Cable', type: ['upper', 'push'], target: ['triceps'], synergist: ['cable pull through', 'cable'] },
  { name: 'Cable Pull Through, Cable', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Cable Twist, Barbell', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'back', 'glutes'] },
  { name: 'Cable Twist, Cable', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'back', 'glutes'] },
  { name: 'Cable Twist, Band', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'back', 'glutes'] },
  { name: 'Cable Twist, Bodyweight', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'back', 'glutes'] },
  { name: 'Cable Twist, Leverage Machine', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'back', 'glutes'] },
  { name: 'Calf Press on Leg Press, Leverage Machine', type: ['lower', 'legs'], target: ['calves'], synergist: ['calf press on seated leg press', 'leverage machine'] },
  { name: 'Calf Press on Seated Leg Press, Leverage Machine', type: ['lower', 'legs'], target: ['calves'], synergist: ['chest dip', 'bodyweight'] },
  { name: 'Chest Dip, Bodyweight', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'back', 'triceps'] },
  { name: 'Chest Fly, Barbell', type: ['upper', 'push'], target: ['chest'], synergist: ['biceps', 'shoulders'] },
  { name: 'Chest Fly, Cable', type: ['upper', 'push'], target: ['chest'], synergist: ['biceps', 'shoulders'] },
  { name: 'Chest Fly, Dumbbell', type: ['upper', 'push'], target: ['chest'], synergist: ['biceps', 'shoulders'] },
  { name: 'Chest Fly, Leverage Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['biceps', 'shoulders'] },
  { name: 'Chest Press, Band', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Chest Press, Leverage Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Chin Up, Bodyweight', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Chin Up, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Clean, Barbell', type: ['upper', 'lower', 'push'], target: ['glutes', 'hamstrings', 'quadriceps', 'back', 'shoulders'], synergist: ['calves', 'biceps', 'chest', 'forearms'] },
  { name: 'Clean and Jerk, Barbell', type: ['upper', 'lower', 'push'], target: ['glutes', 'hamstrings', 'quadriceps', 'back', 'shoulders'], synergist: ['calves', 'biceps', 'chest', 'forearms'] },
  { name: 'Concentration Curl, Barbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Concentration Curl, Cable', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Concentration Curl, Dumbbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Concentration Curl, Band', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Cross Body Crunch, Bodyweight', type: ['core'], target: ['abs'], synergist: ['crunch', 'cable'] },
  { name: 'Crunch, Cable', type: ['core'], target: ['abs'], synergist: ['crunch', 'bodyweight'] },
  { name: 'Crunch, Bodyweight', type: ['core'], target: ['abs'], synergist: ['crunch', 'leverage machine'] },
  { name: 'Crunch, Leverage Machine', type: ['core'], target: ['abs'], synergist: ['deadlift', 'barbell'] },
  { name: 'Deadlift, Barbell', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Deadlift, Cable', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Deadlift, Dumbbell', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Deadlift, Smith Machine', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Deadlift, Band', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Deadlift, Kettlebell', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Deadlift, Leverage Machine', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Deadlift High Pull, Barbell', type: ['upper', 'lower', 'pull'], target: ['shoulders', 'glutes', 'quadriceps'], synergist: ['hamstrings', 'biceps', 'forearms', 'calves', 'back'] },
  { name: 'Decline Bench Press, Dumbbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Decline Bench Press, Smith Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Deficit Deadlift, Barbell', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'back', 'quadriceps', 'calves'] },
  { name: 'Deficit Deadlift, Trap Bar', type: ['lower', 'pull'], target: ['glutes'], synergist: ['hamstrings', 'back', 'quadriceps', 'calves'] },
  { name: 'Elliptical Machine, Leverage Machine', type: ['lower', 'legs'], target: ['glutes', 'quadriceps', 'hamstrings', 'calves'], synergist: ['biceps', 'forearms', 'shoulders', 'glutes', 'hamstrings', 'back', 'chest', 'quadriceps'] },
  { name: 'Face Pull, Band', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['biceps', 'forearms', 'back'] },
  { name: 'Farmer Carry', type: ['upper'], target: ['forearms'], synergist: ['biceps', 'triceps', 'shoulders'] },
  { name: 'Flat Knee Raise, Bodyweight', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'glutes'] },
  { name: 'Flat Leg Raise, Bodyweight', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'glutes'] },
  { name: 'Front Raise, Barbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Front Raise, Cable', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Front Raise, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Front Raise, Band', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Front Raise, Bodyweight', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Front Squat, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Front Squat, Cable', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Front Squat, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Front Squat, Smith Machine', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Front Squat, Kettlebell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Glute Bridge, Barbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Glute Bridge, Dumbbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Glute Bridge, Band', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Glute Bridge March, Bodyweight', type: ['lower', 'legs'], target: ['glutes', 'abs'], synergist: ['hamstrings', 'quadriceps'] },
  { name: 'Glute Kickback, Cable', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Glute Kickback, Band', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Goblet Squat, Dumbbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Goblet Squat, Kettlebell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Good Morning, Barbell', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['glutes'] },
  { name: 'Good Morning, Smith Machine', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['glutes'] },
  { name: 'Good Morning, Leverage Machine', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['glutes'] },
  { name: 'Hack Squat, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Hack Squat, Smith Machine', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Hammer Curl, Cable', type: ['upper', 'pull'], target: ['forearms'], synergist: ['biceps'] },
  { name: 'Hammer Curl, Dumbbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['biceps'] },
  { name: 'Hammer Curl, Band', type: ['upper', 'pull'], target: ['forearms'], synergist: ['biceps'] },
  { name: 'Handstand Push Up, Bodyweight', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Hang Clean, Kettlebell', type: ['upper', 'lower', 'pull'], target: ['biceps', 'forearms'], synergist: ['shoulders', 'chest'] },
  { name: 'Hanging Leg Raise, Cable', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'glutes'] },
  { name: 'Hanging Leg Raise, Bodyweight', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'glutes'] },
  { name: 'High Row, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'High Row, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Hip Abductor, Cable', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hip abductor', 'band'] },
  { name: 'Hip Abductor, Band', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hip abductor', 'bodyweight'] },
  { name: 'Hip Abductor, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hip abductor', 'leverage machine'] },
  { name: 'Hip Abductor, Leverage Machine', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hip adductor', 'leverage machine'] },
  { name: 'Hip Adductor, Leverage Machine', type: ['lower', 'legs'], target: ['hamstrings', 'quadriceps'], synergist: ['hip thrust', 'barbell'] },
  { name: 'Hip Thrust, Barbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Hip Thrust, Band', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Hip Thrust, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Hip Thrust, Leverage Machine', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Incline Bench Press, Barbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Bench Press, Cable', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Bench Press, Dumbbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Bench Press, Smith Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Bench Press Wide Grip, Barbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Chest Fly, Cable', type: ['upper', 'push'], target: ['chest'], synergist: ['biceps', 'shoulders'] },
  { name: 'Incline Chest Fly, Dumbbell', type: ['upper', 'push'], target: ['chest'], synergist: ['biceps', 'shoulders'] },
  { name: 'Incline Chest Press, Dumbbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Chest Press, Band', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Chest Press, Leverage Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Incline Curl, Dumbbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Incline Row, Barbell', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Incline Row, Dumbbell', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Inverted Row, Bodyweight', type: ['upper', 'pull'], target: ['back'], synergist: ['shoulders', 'biceps', 'forearms', 'chest'] },
  { name: 'Jackknife Sit Up, Bodyweight', type: ['core'], target: ['abs'], synergist: ['quadriceps', 'glutes'] },
  { name: 'Jump Squat, Barbell', type: ['lower', 'legs'], target: ['glutes', 'quadriceps'], synergist: ['hamstrings', 'calves'] },
  { name: 'Jump Squat, Bodyweight', type: ['lower', 'legs'], target: ['glutes', 'quadriceps'], synergist: ['hamstrings', 'calves'] },
  { name: 'Kettlebell Swing, Dumbbell', type: ['upper', 'lower', 'core'], target: ['shoulders', 'glutes'], synergist: ['hamstrings', 'chest', 'calves'] },
  { name: 'Kettlebell Swing, Kettlebell', type: ['upper', 'lower', 'core'], target: ['shoulders', 'glutes'], synergist: ['hamstrings', 'chest', 'calves'] },
  { name: 'Kneeling Pulldown, Band', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest', 'triceps'] },
  { name: 'Knees to Elbows, Bodyweight', type: ['core'], target: ['abs'], synergist: ['hamstrings', 'quadriceps', 'glutes'] },
  { name: 'Lat Pulldown, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders'] },
  { name: 'Lat Pulldown, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders'] },
  { name: 'Lateral Raise, Cable', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Lateral Raise, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Lateral Raise, Band', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Lateral Raise, Kettlebell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Lateral Raise, Leverage Machine', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Leg Extension, Band', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['leg extension', 'leverage machine'] },
  { name: 'Leg Extension, Leverage Machine', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['leg press', 'smith machine'] },
  { name: 'Leg Press, Smith Machine', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Leg Press, Leverage Machine', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Legs Up Bench Press, Barbell', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Lunge, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Lunge, Cable', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Lunge, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Lunge, Bodyweight', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Lying Bicep Curl, Cable', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Lying Bicep Curl, Dumbbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Lying Leg Curl, Band', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['calves', 'quadriceps'] },
  { name: 'Lying Leg Curl, Leverage Machine', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['calves', 'quadriceps'] },
  { name: 'Muscle Up, Bodyweight', type: ['upper', 'pull'], target: ['biceps', 'forearms', 'shoulders', 'back', 'chest', 'triceps'], synergist: ['oblique crunch', 'bodyweight'] },
  { name: 'Oblique Crunch, Bodyweight', type: ['core'], target: ['abs'], synergist: ['overhead press', 'barbell'] },
  { name: 'Overhead Press, Barbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Overhead Press, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Overhead Press, EZ Bar', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Overhead Squat, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Overhead Squat, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Pec Deck, Leverage Machine', type: ['upper', 'push'], target: ['chest'], synergist: ['pendlay row', 'barbell'] },
  { name: 'Pendlay Row, Barbell', type: ['upper', 'pull'], target: ['shoulders', 'back'], synergist: ['biceps', 'forearms', 'chest'] },
  { name: 'Pistol Squat, Kettlebell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Pistol Squat, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Pistol Squat, Leverage Machine', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Plank, Bodyweight', type: ['core'], target: ['abs'], synergist: ['preacher curl', 'barbell'] },
  { name: 'Preacher Curl, Barbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Preacher Curl, Dumbbell', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Preacher Curl, Leverage Machine', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Preacher Curl, EZ Bar', type: ['upper', 'pull'], target: ['biceps'], synergist: ['forearms'] },
  { name: 'Pull Up, Band', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders'] },
  { name: 'Pull Up, Bodyweight', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders'] },
  { name: 'Pull Up, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders'] },
  { name: 'Pullover, Barbell', type: ['upper', 'pull'], target: ['back'], synergist: ['shoulders', 'chest', 'triceps'] },
  { name: 'Pullover, Dumbbell', type: ['upper', 'pull'], target: ['back'], synergist: ['shoulders', 'chest', 'triceps'] },
  { name: 'Push Press, Barbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['biceps', 'chest'] },
  { name: 'Push Press, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['biceps', 'chest'] },
  { name: 'Push Press, Kettlebell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['biceps', 'chest'] },
  { name: 'Push Press, Bodyweight', type: ['upper', 'push'], target: ['shoulders'], synergist: ['biceps', 'chest'] },
  { name: 'Push Up, Band', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Push Up, Bodyweight', type: ['upper', 'push'], target: ['chest'], synergist: ['shoulders', 'triceps'] },
  { name: 'Reverse Crunch, Cable', type: ['core'], target: ['abs'], synergist: ['reverse crunch', 'bodyweight'] },
  { name: 'Reverse Crunch, Bodyweight', type: ['core'], target: ['abs'], synergist: ['reverse curl', 'barbell'] },
  { name: 'Reverse Curl, Barbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['biceps'] },
  { name: 'Reverse Curl, Cable', type: ['upper', 'pull'], target: ['forearms'], synergist: ['biceps'] },
  { name: 'Reverse Curl, Dumbbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['biceps'] },
  { name: 'Reverse Curl, Band', type: ['upper', 'pull'], target: ['forearms'], synergist: ['biceps'] },
  { name: 'Reverse Fly, Dumbbell', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['back'] },
  { name: 'Reverse Fly, Band', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['back'] },
  { name: 'Reverse Fly, Leverage Machine', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['back'] },
  { name: 'Reverse Hyperextension, Band', type: ['core', 'lower'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Reverse Hyperextension, Leverage Machine', type: ['core', 'lower'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Reverse Lunge, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'calves', 'glutes'] },
  { name: 'Reverse Lunge, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'calves', 'glutes'] },
  { name: 'Reverse Lunge, Kettlebell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'calves', 'glutes'] },
  { name: 'Reverse Lunge, Bodyweight', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'calves', 'glutes'] },
  { name: 'Reverse Wrist Curl, Barbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['reverse wrist curl', 'dumbbell'] },
  { name: 'Reverse Wrist Curl, Dumbbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['reverse wrist curl', 'ez bar'] },
  { name: 'Reverse Wrist Curl, EZ Bar', type: ['upper', 'pull'], target: ['forearms'], synergist: ['romanian deadlift', 'barbell'] },
  { name: 'Romanian Deadlift, Barbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'back'] },
  { name: 'Romanian Deadlift, Dumbbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'back'] },
  { name: 'Russian Twist, Cable', type: ['core'], target: ['abs'], synergist: ['back'] },
  { name: 'Russian Twist, Dumbbell', type: ['core'], target: ['abs'], synergist: ['back'] },
  { name: 'Russian Twist, Bodyweight', type: ['core'], target: ['abs'], synergist: ['back'] },
  { name: 'Safety Squat Bar Squat, Barbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Seated Calf Raise, Barbell', type: ['lower', 'legs'], target: ['calves'], synergist: ['seated calf raise', 'dumbbell'] },
  { name: 'Seated Calf Raise, Dumbbell', type: ['lower', 'legs'], target: ['calves'], synergist: ['seated calf raise', 'leverage machine'] },
  { name: 'Seated Calf Raise, Leverage Machine', type: ['lower', 'legs'], target: ['calves'], synergist: ['seated front raise', 'barbell'] },
  { name: 'Seated Front Raise, Barbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Seated Front Raise, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back'] },
  { name: 'Seated Leg Curl, Leverage Machine', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['calves', 'quadriceps'] },
  { name: 'Seated Leg Press, Leverage Machine', type: ['lower', 'legs'], target: ['glutes', 'quadriceps'], synergist: ['hamstrings', 'calves'] },
  { name: 'Seated Overhead Press, Barbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Seated Palms Up Wrist Curl, Dumbbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['seated row', 'cable'] },
  { name: 'Seated Row, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Seated Row, Band', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Seated Row, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Seated Wide Grip Row, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Shoulder Press, Cable', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Shoulder Press, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Shoulder Press, Smith Machine', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Shoulder Press, Band', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Shoulder Press, Leverage Machine', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Shoulder Press Parallel Grip, Dumbbell', type: ['upper', 'push'], target: ['shoulders'], synergist: ['chest', 'back', 'triceps'] },
  { name: 'Shrug, Barbell', type: ['upper', 'pull'], target: ['back'], synergist: ['shrug', 'cable'] },
  { name: 'Shrug, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['shrug', 'dumbbell'] },
  { name: 'Shrug, Dumbbell', type: ['upper', 'pull'], target: ['back'], synergist: ['shrug', 'smith machine'] },
  { name: 'Shrug, Smith Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['shrug', 'band'] },
  { name: 'Shrug, Band', type: ['upper', 'pull'], target: ['back'], synergist: ['shrug', 'leverage machine'] },
  { name: 'Shrug, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['side bend', 'cable'] },
  { name: 'Side Bend, Cable', type: ['core'], target: ['abs'], synergist: ['back'] },
  { name: 'Side Bend, Dumbbell', type: ['core'], target: ['abs'], synergist: ['back'] },
  { name: 'Side Bend, Band', type: ['core'], target: ['abs'], synergist: ['back'] },
  { name: 'Side Crunch, Cable', type: ['core'], target: ['abs'], synergist: ['side crunch', 'band'] },
  { name: 'Side Crunch, Band', type: ['core'], target: ['abs'], synergist: ['side crunch', 'bodyweight'] },
  { name: 'Side Crunch, Bodyweight', type: ['core'], target: ['abs'], synergist: ['side hip abductor', 'barbell'] },
  { name: 'Side Hip Abductor, Barbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['side hip abductor', 'bodyweight'] },
  { name: 'Side Hip Abductor, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['side hip abductor', 'leverage machine'] },
  { name: 'Side Hip Abductor, Leverage Machine', type: ['lower', 'legs'], target: ['glutes'], synergist: ['side lying clam', 'bodyweight'] },
  { name: 'Side Lying Clam, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['side plank', 'bodyweight'] },
  { name: 'Side Plank, Bodyweight', type: ['core'], target: ['abs'], synergist: ['single leg bridge', 'bodyweight'] },
  { name: 'Single Leg Bridge, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Single Leg Deadlift, Dumbbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Single Leg Deadlift, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings'] },
  { name: 'Single Leg Glute Bridge Bent Knee, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['single leg glute bridge on bench', 'bodyweight'] },
  { name: 'Single Leg Glute Bridge On Bench, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['single leg glute bridge straight leg', 'bodyweight'] },
  { name: 'Single Leg Glute Bridge Straight Leg, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['single leg hip thrust', 'barbell'] },
  { name: 'Single Leg Hip Thrust, Barbell', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Single Leg Hip Thrust, Bodyweight', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Single Leg Hip Thrust, Leverage Machine', type: ['lower', 'legs'], target: ['glutes'], synergist: ['quadriceps'] },
  { name: 'Sissy Squat, Bodyweight', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings'] },
  { name: 'Sit Up, Kettlebell', type: ['core'], target: ['abs'], synergist: ['quadriceps', 'glutes'] },
  { name: 'Sit Up, Bodyweight', type: ['core'], target: ['abs'], synergist: ['quadriceps', 'glutes'] },
  { name: 'Skullcrusher, Barbell', type: ['upper', 'push'], target: ['triceps'], synergist: ['skullcrusher', 'cable'] },
  { name: 'Skullcrusher, Cable', type: ['upper', 'push'], target: ['triceps'], synergist: ['skullcrusher', 'dumbbell'] },
  { name: 'Skullcrusher, Dumbbell', type: ['upper', 'push'], target: ['triceps'], synergist: ['skullcrusher', 'ez bar'] },
  { name: 'Skullcrusher, EZ Bar', type: ['upper', 'push'], target: ['triceps'], synergist: ['snatch', 'dumbbell'] },
  { name: 'Snatch, Dumbbell', type: ['upper', 'lower', 'pull'], target: ['shoulders', 'back', 'glutes', 'quadriceps'], synergist: ['hamstrings', 'calves', 'chest', 'triceps'] },
  { name: 'Split Squat, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Split Squat, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Split Squat, Band', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Split Squat, Kettlebell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Split Squat, Bodyweight', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Squat, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Squat, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Squat, Smith Machine', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Squat, Bodyweight', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Squat, Leverage Machine', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Squat Row, Band', type: ['upper', 'lower', 'pull'], target: ['glutes', 'back'], synergist: ['shoulders', 'hamstrings', 'chest', 'quadriceps', 'calves'] },
  { name: 'Standing Calf Raise, Barbell', type: ['lower', 'legs'], target: ['calves'], synergist: ['standing calf raise', 'cable'] },
  { name: 'Standing Calf Raise, Cable', type: ['lower', 'legs'], target: ['calves'], synergist: ['standing calf raise', 'dumbbell'] },
  { name: 'Standing Calf Raise, Dumbbell', type: ['lower', 'legs'], target: ['calves'], synergist: ['standing calf raise', 'bodyweight'] },
  { name: 'Standing Calf Raise, Bodyweight', type: ['lower', 'legs'], target: ['calves'], synergist: ['standing calf raise', 'leverage machine'] },
  { name: 'Standing Calf Raise, Leverage Machine', type: ['lower', 'legs'], target: ['calves'], synergist: ['standing row', 'cable'] },
  { name: 'Standing Row, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Standing Row Close Grip, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['shoulders', 'biceps', 'forearms'] },
  { name: 'Standing Row Rear Delt With Rope, Cable', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['biceps', 'forearms', 'back'] },
  { name: 'Standing Row Rear Delt, Horizontal, With Rope, Cable', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['back'] },
  { name: 'Standing Row V-Bar, Cable', type: ['upper', 'pull'], target: ['back'], synergist: ['shoulders', 'biceps', 'forearms', 'chest'] },
  { name: 'Step up, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Step up, Dumbbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Step up, Band', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Step up, Bodyweight', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
  { name: 'Stiff Leg Deadlift, Barbell', type: ['lower', 'legs'], target: ['back'], synergist: ['hamstrings', 'glutes'] },
  { name: 'Stiff Leg Deadlift, Dumbbell', type: ['lower', 'legs'], target: ['back'], synergist: ['hamstrings', 'glutes'] },
  { name: 'Stiff Leg Deadlift, Band', type: ['lower', 'legs'], target: ['back'], synergist: ['hamstrings', 'glutes'] },
  { name: 'Straight Leg Deadlift, Barbell', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['back', 'glutes'] },
  { name: 'Straight Leg Deadlift, Dumbbell', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['back', 'glutes'] },
  { name: 'Straight Leg Deadlift, Band', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['back', 'glutes'] },
  { name: 'Straight Leg Deadlift, Kettlebell', type: ['lower', 'legs'], target: ['hamstrings'], synergist: ['back', 'glutes'] },
  { name: 'Sumo Deadlift, Barbell', type: ['lower', 'legs'], target: ['back'], synergist: ['hamstrings', 'glutes', 'quadriceps', 'calves'] },
  { name: 'Sumo Deadlift High Pull, Barbell', type: ['upper', 'lower', 'pull'], target: ['shoulders', 'glutes', 'quadriceps'], synergist: ['hamstrings', 'biceps', 'forearms', 'calves', 'back'] },
  { name: 'Superman, Dumbbell', type: ['core'], target: ['back'], synergist: ['glutes', 'hamstrings'] },
  { name: 'Superman, Bodyweight', type: ['core'], target: ['back'], synergist: ['glutes', 'hamstrings'] },
  { name: 'T Bar Row, Leverage Machine', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Thruster, Barbell', type: ['upper', 'lower', 'push'], target: ['shoulders', 'glutes', 'quadriceps'], synergist: ['hamstrings', 'chest', 'calves', 'triceps'] },
  { name: 'Toes To Bar, Bodyweight', type: ['core'], target: ['abs'], synergist: ['quadriceps', 'glutes'] },
  { name: 'Trap Bar Deadlift, Trap Bar', type: ['lower', 'legs'], target: ['glutes'], synergist: ['hamstrings', 'quadriceps', 'calves'] },
  { name: 'Running, Indoor', type: ['lower', 'legs'], target: ['glutes', 'quadriceps', 'hamstrings', 'calves'], synergist: ['biceps', 'forearms', 'shoulders', 'glutes', 'hamstrings', 'back', 'chest', 'quadriceps'] },
  { name: 'Running, Outdoor', type: ['lower', 'legs'], target: ['glutes', 'quadriceps', 'hamstrings', 'calves'], synergist: ['biceps', 'forearms', 'shoulders', 'glutes', 'hamstrings', 'back', 'chest', 'quadriceps'] },
  { name: 'Triceps Dip, Bodyweight', type: ['upper', 'push'], target: ['triceps'], synergist: ['shoulders', 'back', 'chest'] },
  { name: 'Triceps Dip, Leverage Machine', type: ['upper', 'push'], target: ['triceps'], synergist: ['shoulders', 'back', 'chest'] },
  { name: 'Triceps Extension, Barbell', type: ['upper', 'push'], target: ['triceps'], synergist: ['triceps extension', 'cable'] },
  { name: 'Triceps Extension, Cable', type: ['upper', 'push'], target: ['triceps'], synergist: ['triceps extension', 'dumbbell'] },
  { name: 'Triceps Extension, Dumbbell', type: ['upper', 'push'], target: ['triceps'], synergist: ['triceps extension', 'band'] },
  { name: 'Triceps Extension, Band', type: ['upper', 'push'], target: ['triceps'], synergist: ['triceps pushdown', 'cable'] },
  { name: 'Triceps Pushdown, Cable', type: ['upper', 'push'], target: ['triceps'], synergist: ['upright row', 'barbell'] },
  { name: 'Upright Row, Barbell', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['biceps', 'forearms', 'chest', 'back'] },
  { name: 'Upright Row, Cable', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['biceps', 'forearms', 'chest', 'back'] },
  { name: 'Upright Row, Dumbbell', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['biceps', 'forearms', 'chest', 'back'] },
  { name: 'Upright Row, Band', type: ['upper', 'pull'], target: ['shoulders'], synergist: ['biceps', 'forearms', 'chest', 'back'] },
  { name: 'V Up, Dumbbell', type: ['core'], target: ['abs'], synergist: ['quadriceps', 'glutes'] },
  { name: 'V Up, Band', type: ['core'], target: ['abs'], synergist: ['quadriceps', 'glutes'] },
  { name: 'V Up, Bodyweight', type: ['core'], target: ['abs'], synergist: ['quadriceps', 'glutes'] },
  { name: 'Wide Pull Up, Bodyweight', type: ['upper', 'pull'], target: ['back'], synergist: ['biceps', 'forearms', 'shoulders', 'chest'] },
  { name: 'Wrist Curl, Barbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['wrist curl', 'dumbbell'] },
  { name: 'Wrist Curl, Dumbbell', type: ['upper', 'pull'], target: ['forearms'], synergist: ['wrist curl', 'ez bar'] },
  { name: 'Wrist Curl, EZ Bar', type: ['upper', 'pull'], target: ['forearms'], synergist: ['wrist roller', 'bodyweight'] },
  { name: 'Wrist Roller, Bodyweight', type: ['upper', 'pull'], target: ['forearms'], synergist: ['zercher squat', 'barbell'] },
  { name: 'Zercher Squat, Barbell', type: ['lower', 'legs'], target: ['quadriceps'], synergist: ['hamstrings', 'glutes', 'calves'] },
]

export function findExerciseByName(name: string): ExerciseLibraryItem | undefined {
  return EXERCISE_LIBRARY.find(ex => ex.name.toLowerCase() === name.trim().toLowerCase())
}
